// Code generated by protoc-gen-go.
// source: natsproxy.proto
// DO NOT EDIT!

/*
Package natsproxy is a generated protocol buffer package.

It is generated from these files:
	natsproxy.proto

It has these top-level messages:
	FormItem
	FormMap
	HeaderItem
	HeaderMap
	Request
	Response
*/
package natsproxy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type FormItem struct {
	Key              *string  `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value            []string `protobuf:"bytes,2,rep,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *FormItem) Reset()                    { *m = FormItem{} }
func (m *FormItem) String() string            { return proto.CompactTextString(m) }
func (*FormItem) ProtoMessage()               {}
func (*FormItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FormItem) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *FormItem) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type FormMap struct {
	Items            []*FormItem `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *FormMap) Reset()                    { *m = FormMap{} }
func (m *FormMap) String() string            { return proto.CompactTextString(m) }
func (*FormMap) ProtoMessage()               {}
func (*FormMap) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FormMap) GetItems() []*FormItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type HeaderItem struct {
	Key              *string  `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value            []string `protobuf:"bytes,2,rep,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *HeaderItem) Reset()                    { *m = HeaderItem{} }
func (m *HeaderItem) String() string            { return proto.CompactTextString(m) }
func (*HeaderItem) ProtoMessage()               {}
func (*HeaderItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HeaderItem) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *HeaderItem) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type HeaderMap struct {
	Items            []*HeaderItem `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *HeaderMap) Reset()                    { *m = HeaderMap{} }
func (m *HeaderMap) String() string            { return proto.CompactTextString(m) }
func (*HeaderMap) ProtoMessage()               {}
func (*HeaderMap) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *HeaderMap) GetItems() []*HeaderItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type Request struct {
	URL              *string    `protobuf:"bytes,1,opt,name=URL,json=uRL" json:"URL,omitempty"`
	Method           *string    `protobuf:"bytes,2,opt,name=Method,json=method" json:"Method,omitempty"`
	RemoteAddr       *string    `protobuf:"bytes,3,opt,name=RemoteAddr,json=remoteAddr" json:"RemoteAddr,omitempty"`
	Body             []byte     `protobuf:"bytes,4,opt,name=Body,json=body" json:"Body,omitempty"`
	Form             *FormMap   `protobuf:"bytes,5,opt,name=Form,json=form" json:"Form,omitempty"`
	Header           *HeaderMap `protobuf:"bytes,6,opt,name=Header,json=header" json:"Header,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Request) GetURL() string {
	if m != nil && m.URL != nil {
		return *m.URL
	}
	return ""
}

func (m *Request) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *Request) GetRemoteAddr() string {
	if m != nil && m.RemoteAddr != nil {
		return *m.RemoteAddr
	}
	return ""
}

func (m *Request) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Request) GetForm() *FormMap {
	if m != nil {
		return m.Form
	}
	return nil
}

func (m *Request) GetHeader() *HeaderMap {
	if m != nil {
		return m.Header
	}
	return nil
}

type Response struct {
	StatusCode       *int32     `protobuf:"varint,1,opt,name=StatusCode,json=statusCode" json:"StatusCode,omitempty"`
	Header           *HeaderMap `protobuf:"bytes,2,opt,name=Header,json=header" json:"Header,omitempty"`
	Body             []byte     `protobuf:"bytes,3,opt,name=Body,json=body" json:"Body,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Response) GetStatusCode() int32 {
	if m != nil && m.StatusCode != nil {
		return *m.StatusCode
	}
	return 0
}

func (m *Response) GetHeader() *HeaderMap {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*FormItem)(nil), "FormItem")
	proto.RegisterType((*FormMap)(nil), "FormMap")
	proto.RegisterType((*HeaderItem)(nil), "HeaderItem")
	proto.RegisterType((*HeaderMap)(nil), "HeaderMap")
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
}

var fileDescriptor0 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x50, 0xcd, 0x4a, 0xf4, 0x30,
	0x14, 0xa5, 0xd3, 0x9f, 0x69, 0x6f, 0x3f, 0xf8, 0x24, 0x88, 0x64, 0x21, 0x3a, 0x76, 0x35, 0xb8,
	0xc8, 0xa2, 0xf8, 0x02, 0x2a, 0x88, 0xc2, 0xcc, 0xe6, 0x8a, 0x0f, 0xd0, 0x21, 0x57, 0x46, 0xb4,
	0x93, 0xda, 0xa4, 0x62, 0x1f, 0xc9, 0xb7, 0x34, 0x49, 0x6d, 0x47, 0x17, 0x2e, 0xdc, 0x84, 0x73,
	0xcf, 0xe5, 0xfc, 0xdc, 0xc0, 0xff, 0x5d, 0x65, 0x74, 0xd3, 0xaa, 0xf7, 0x5e, 0xd8, 0xd7, 0xa8,
	0xa2, 0x84, 0xf4, 0x46, 0xb5, 0xf5, 0x9d, 0xa1, 0x9a, 0x1d, 0x40, 0xf8, 0x4c, 0x3d, 0x0f, 0x16,
	0xc1, 0x32, 0x43, 0x07, 0xd9, 0x21, 0xc4, 0x6f, 0xd5, 0x4b, 0x47, 0x7c, 0xb6, 0x08, 0x2d, 0x37,
	0x0c, 0xc5, 0x39, 0xcc, 0x9d, 0x66, 0x5d, 0x35, 0xec, 0x14, 0xe2, 0x27, 0x2b, 0xd5, 0x56, 0x14,
	0x2e, 0xf3, 0x32, 0x13, 0xa3, 0x19, 0x0e, 0x7c, 0x71, 0x01, 0x70, 0x4b, 0x95, 0xa4, 0xf6, 0x4f,
	0x09, 0x02, 0xb2, 0x41, 0xe5, 0x32, 0xce, 0x7e, 0x66, 0xe4, 0x62, 0x6f, 0x38, 0xa6, 0x7c, 0x04,
	0x30, 0x47, 0x7a, 0xed, 0x48, 0x1b, 0x97, 0xf1, 0x80, 0xab, 0x31, 0xa3, 0xc3, 0x15, 0x3b, 0x82,
	0x64, 0x4d, 0x66, 0xab, 0xa4, 0x0d, 0x71, 0x64, 0x52, 0xfb, 0x89, 0x9d, 0x00, 0x20, 0xd5, 0xca,
	0xd0, 0xa5, 0x94, 0x2d, 0x0f, 0xfd, 0x0e, 0xda, 0x89, 0x61, 0x0c, 0xa2, 0x2b, 0x25, 0x7b, 0x1e,
	0xd9, 0xcd, 0x3f, 0x8c, 0x36, 0x16, 0xb3, 0x63, 0x88, 0xdc, 0x89, 0x3c, 0xb6, 0x5c, 0x5e, 0xa6,
	0xe2, 0xeb, 0x23, 0x30, 0x7a, 0xb4, 0x80, 0x15, 0x90, 0x0c, 0xe5, 0x78, 0xe2, 0xf7, 0x20, 0xa6,
	0x33, 0x30, 0xd9, 0x7a, 0x58, 0x6c, 0x20, 0x45, 0xd2, 0x8d, 0xda, 0x69, 0x72, 0x0d, 0xee, 0x4d,
	0x65, 0x3a, 0x7d, 0xad, 0x24, 0xf9, 0xca, 0x31, 0x82, 0x9e, 0x98, 0x6f, 0x7e, 0xb3, 0xdf, 0xfc,
	0xa6, 0x96, 0xe1, 0xbe, 0xe5, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x05, 0x5a, 0xe5, 0xb8, 0xe7,
	0x01, 0x00, 0x00,
}
