// Code generated by protoc-gen-go.
// source: protobuf.proto
// DO NOT EDIT!

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	protobuf.proto

It has these top-level messages:
	Value
	Values
	Request
	Response
*/
package natsproxy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Value struct {
	Key              *string  `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value            []string `protobuf:"bytes,2,rep,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Value) Reset()                    { *m = Value{} }
func (m *Value) String() string            { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()               {}
func (*Value) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Value) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *Value) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type Values struct {
	Items            []*Value `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Values) Reset()                    { *m = Values{} }
func (m *Values) String() string            { return proto.CompactTextString(m) }
func (*Values) ProtoMessage()               {}
func (*Values) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Values) GetItems() []*Value {
	if m != nil {
		return m.Items
	}
	return nil
}

type Request struct {
	URL              *string `protobuf:"bytes,1,opt,name=URL,json=uRL" json:"URL,omitempty"`
	Method           *string `protobuf:"bytes,2,opt,name=Method,json=method" json:"Method,omitempty"`
	RemoteAddr       *string `protobuf:"bytes,3,opt,name=RemoteAddr,json=remoteAddr" json:"RemoteAddr,omitempty"`
	Body             []byte  `protobuf:"bytes,4,opt,name=Body,json=body" json:"Body,omitempty"`
	Form             *Values `protobuf:"bytes,5,opt,name=Form,json=form" json:"Form,omitempty"`
	Header           *Values `protobuf:"bytes,6,opt,name=Header,json=header" json:"Header,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Request) GetURL() string {
	if m != nil && m.URL != nil {
		return *m.URL
	}
	return ""
}

func (m *Request) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *Request) GetRemoteAddr() string {
	if m != nil && m.RemoteAddr != nil {
		return *m.RemoteAddr
	}
	return ""
}

func (m *Request) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Request) GetForm() *Values {
	if m != nil {
		return m.Form
	}
	return nil
}

func (m *Request) GetHeader() *Values {
	if m != nil {
		return m.Header
	}
	return nil
}

type Response struct {
	StatusCode       *int32  `protobuf:"varint,1,opt,name=StatusCode,json=statusCode" json:"StatusCode,omitempty"`
	Header           *Values `protobuf:"bytes,2,opt,name=Header,json=header" json:"Header,omitempty"`
	Body             []byte  `protobuf:"bytes,3,opt,name=Body,json=body" json:"Body,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Response) GetStatusCode() int32 {
	if m != nil && m.StatusCode != nil {
		return *m.StatusCode
	}
	return 0
}

func (m *Response) GetHeader() *Values {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Value)(nil), "Value")
	proto.RegisterType((*Values)(nil), "Values")
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Response)(nil), "Response")
}

var fileDescriptor0 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x8e, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0xc6, 0x69, 0xf3, 0xa7, 0x3a, 0x15, 0x91, 0x41, 0x24, 0xa0, 0x68, 0xd9, 0x83, 0xf4, 0x54,
	0xa1, 0x6f, 0xa0, 0x82, 0x78, 0xa8, 0x97, 0x11, 0xbd, 0xca, 0x96, 0x4c, 0xa9, 0xe8, 0x9a, 0x9a,
	0x64, 0x85, 0x3e, 0x90, 0xef, 0x69, 0x92, 0xc5, 0x55, 0xc1, 0xdb, 0xcc, 0xef, 0xcb, 0xfc, 0xf2,
	0xc1, 0xfe, 0xc6, 0xbb, 0xe8, 0x96, 0xed, 0x6a, 0x56, 0x86, 0xea, 0x02, 0xd4, 0x63, 0xfd, 0xda,
	0x32, 0x1e, 0x80, 0x78, 0xe1, 0xad, 0x19, 0x4c, 0x06, 0xd3, 0x5d, 0xca, 0x23, 0x1e, 0x82, 0xfa,
	0xc8, 0x91, 0x19, 0x4e, 0x44, 0x62, 0xdd, 0x52, 0x9d, 0x83, 0x2e, 0x07, 0x01, 0x4f, 0x40, 0x3d,
	0x47, 0x6e, 0x42, 0xba, 0x11, 0xd3, 0xf1, 0x5c, 0xcf, 0x0a, 0xa7, 0x0e, 0x56, 0x9f, 0x03, 0x18,
	0x11, 0xbf, 0xa7, 0x87, 0x31, 0xbb, 0x1f, 0x68, 0xf1, 0xed, 0x6e, 0x69, 0x81, 0x47, 0xa0, 0xef,
	0x38, 0xae, 0x9d, 0x4d, 0xf2, 0x0c, 0x75, 0x53, 0x36, 0x3c, 0x05, 0x20, 0x6e, 0x5c, 0xe4, 0x4b,
	0x6b, 0xbd, 0x11, 0x25, 0x03, 0xdf, 0x13, 0x44, 0x90, 0x57, 0xce, 0x6e, 0x8d, 0x4c, 0xc9, 0x1e,
	0xc9, 0x65, 0x9a, 0xf1, 0x18, 0xe4, 0x8d, 0xf3, 0x8d, 0x51, 0x89, 0x8d, 0xe7, 0xa3, 0xae, 0x46,
	0x20, 0xb9, 0x4a, 0x10, 0xcf, 0x40, 0xdf, 0x72, 0x6d, 0xd9, 0x1b, 0xfd, 0x37, 0xd6, 0xeb, 0x82,
	0xab, 0x27, 0xd8, 0x21, 0x0e, 0x1b, 0xf7, 0x16, 0x38, 0xff, 0x7e, 0x1f, 0xeb, 0xd8, 0x86, 0x6b,
	0x67, 0xb9, 0xd4, 0x55, 0x04, 0xa1, 0x27, 0xbf, 0x64, 0xc3, 0x7f, 0x65, 0x7d, 0x3d, 0xf1, 0x53,
	0xef, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x78, 0xf3, 0xa3, 0x1e, 0x72, 0x01, 0x00, 0x00,
}
